---
- hosts: labservers
  become: yes
  tasks:
    - name: Edit Index html
      lineinfile:
        path: /var/www/html/index.html
        line: "I am back"
      when:
        - ansible_hostname == "srv2"
