---
- hosts: labservers
  become: yes
  tasks:
    - name: Installing HTTPD package
      yum: name=httpd state=latest
    - name: Starting HTTPD service
      service: name=httpd state=started enabled=yes
    - name: Creating index.html
      file:
        path: /var/www/html/index.html
        state: touch
    - name: Add a line to index.html
      lineinfile:
        path: /var/www/html/index.html
        line: "Hello World Alhamdu"
    - name: Open HTTP
